#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16gb,walltime=12:00:00
#PBS -N ABCD-HCP-pipeline
#PBS -V

set -e
set -x

export FREESURFER_LICENSE="hayashis@iu.edu 29511 *CPmh9xvKQKHE FSg0ijTusqaQc"
echo $FREESURFER_LICENSE > license.txt

mkdir -p output

#convert input into bids
bl2bids

stage=`jq -r '.stage' config.json`
inT1w=`jq -r '.t1' config.json`
echo "Begin from $stage, continuing through..."

#####################################################################################
#####################################################################################
# some logical checks
if [[ $inT1w = "null" ]] ; then
	echo "app needs minimally a T1w. exiting"
	exit 1
fi

# avoid templateflow problems on HPC's running singularity
mkdir -p templateflow
export SINGULARITYENV_TEMPLATEFLOW_HOME=$PWD/templateflow

# set FreeSurfer
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;

sub=$(jq -r "._inputs[0].meta.subject" config.json | tr -d "_")
if [[ -z $sub || $sub == null ]]; then
    sub=0
fi

#singularity build abcd-hcp-pipeline.img docker://dcanlabs/abcd-hcp-pipeline

singularity exec -e \
  -B `pwd`/bids:/bids \
  -B `pwd`/output:/output \
  docker://dcanlabs/abcd-hcp-pipeline:v0.0.3 \
  /bids /output \
  --freesurfer-license="$FREESURFER_LICENSE" \
  --participant-label $sub \
  --stage $stage \
  --ignore func \
  --ncpus 8
