#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16gb,walltime=12:00:00
#PBS -N ABCD-HCP-pipeline
#PBS -V

set -e
set -x

export FREESURFER_LICENSE="hayashis@iu.edu 29511 *CPmh9xvKQKHE FSg0ijTusqaQc"
echo $FREESURFER_LICENSE > license.txt

mkdir -p output

#convert input into bids
bl2bids

stage=`jq -r '.stage' config.json`
echo "Begin from $stage, continuing through..."

#singularity build abcd-hcp-pipeline.img docker://dcanlabs/abcd-hcp-pipeline

singularity run -e \
  -B `pwd`/bids:/bids \
  -B `pwd`/output:/output \
  -B `pwd`/license.txt:/opt/freesurfer/license.txt \
  docker://dcanlabs/abcd-hcp-pipeline /bids /output --freesurfer-license=/opt/freesurfer/license.txt \
  --stage $stage --ignore func --ncpus 8
